[package]
name = "xmlex"
version = "0.1.0"
authors = ["White-Oak <lpzhelud@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { git = "https://github.com/seanmonstar/reqwest", features = ["blocking"] }
