[package]
name = "xmlex"
version = "0.1.0"
authors = ["White-Oak <lpzhelud@gmail.com>"]
edition = "2018"

[dependencies]
quick-xml = "*"
percent-encoding = "*"
actix-web = "1.0"
reqwest = { version = "0.10.0-alpha.2", features = ["blocking"] }
rust-crypto = "^0.2"
json = "*"
